### ISSUE TITLE
Usage In External Library

### ISSUE THREAD

**Issue by FlipperPlz** [Krzmbrzl/SQF-grammar#1]
Hello [rzmbrzl](https://github.com/Krzmbrzl), I've been working on a few libraries to interact with any and all Bis formats. I was wondering if I would be able to use this grammar for my SQF interaction. The project is [bisutils-kotlin](https://github.com/FlipperPlz/bisutils-kotlin). I plan on keeping your header on the file aswell as a link back to here. I also plan to be editing it somewhat to fit my project scheme. Appreciate you're work making this!

Thanks again, Ryann.

**Comment by Krzmbrzl** [comment]
Sure, feel free to go ahead. I have now also added a license for this project (didn't realize this one didn't have one), so you can simply use this code in accordance with the BSD 3-Clause license, which should grant you all necessary rights. If not, let me now :)
